/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jing_libjpegcompress_CompressUtils */

#ifndef _Included_com_jing_libjpegcompress_CompressUtils
#define _Included_com_jing_libjpegcompress_CompressUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jing_libjpegcompress_CompressUtils
 * Method:    compressBitmap
 * Signature: (Ljava/lang/Object;III[BZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jing_libjpegcompress_CompressUtils_compressBitmap
  (JNIEnv *, jclass, jobject, jint, jint, jint, jbyteArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
